### ISSUE TITLE
This is genius - improvements

### ISSUE THREAD

**Issue by Cubox** [fasmide/capture-all-the-scripts#1]
I found a way to integrate this on my system without changing my ssh port.
I use sshguard to block any attempt at bad things to my ssh daemon, so I just changed the rule to drop any traffic from blacklisted addresses to redirect port 22 to 6666, where your program is silently waiting.

I would suggest having a ebook.txt file already in the repo, I found this link: http://norvig.com/big.txt
If you find it suitable.

I am now patiently waiting for someone to get blacklisted automatically and check if I can send them the sweet, sweet data! Only tested with manually added blacklisted adresses.

**Comment by fasmide** [comment]
> I found a way to integrate this on my system without changing my ssh port.

nice! please share (in the readme of cause :)

> I would suggest having a ebook.txt file already in the repo, I found this link: http://norvig.com/big.txt
> If you find it suitable.

I think ill just add `curl http://norvig.com/big.txt > ebook.txt` to the getting started - that thing is huge btw :)

**Comment by Cubox** [comment]
The way I did it is very specific to my setup, so I don't think details on how to do it would be useful for everyone.
It's huge for a reason ;)

**Comment by Cubox** [comment]
After a bit of testing, my way of doing things is not as efficient as changing ssh's port entirely. Most bots will not try again after the first connection.
Since they only connect to the "honeypot" once they are banned, a very large portion of them never retry and never get spammed as a result.
